version: 1.0.{build}
configuration:
- Debug
- Release
platform:
- Any CPU

build:
  project: YoutubeExtractor\YoutubeExtractor.sln
  parallel: true
  verbosity: detailed

environment:
  matrix:
  - YoutubeExtractor: YoutubeExtractor\YoutubeExtractor.sln

artifacts:
  - path: YoutubeExtractor\YoutubeExtractor\YouTubeDownloader\bin\$(configuration)
    name: YouTubeDownloader

build_script:
- cmd: >-
    cd %YoutubeExtractor%
    nuget restore
    msbuild %YoutubeExtractor% /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
