version: 1.0.{build}
configuration:
- Debug
- Release
platform:
- Any CPU

build:
  project: YoutubeExtractor\YoutubeExtractor.sln
  parallel: true
  verbosity: detailed

environment:
  matrix:
  - YoutubeExtractor: YoutubeExtractor\YoutubeExtractor.sln

before_build:
- cmd: >-
    rem Change Project Directory to install nuget dependencies
    cd %YoutubeExtractor%
    nuget restore

artifacts:
  - path: YoutubeExtractor\YoutubeExtractor\YouTubeDownloader\bin\$(configuration)
    name: YouTubeDownloader

build_script:
- cmd: >-
    msbuild %YoutubeExtractor% /verbosity:detailed /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
